import type { Destination, PlaceCategory, SubCategory, Group } from './types';

/* ── Destination-specific cost data (realistic 2026 prices in USD) ── */
export const CITY_COSTS: Record<string, {
  photoUrl: string;
  landmark: string;
  food: { item: string; price: string }[];
  drinks: { item: string; price: string }[];
  entertainment: { item: string; price: string }[];
}> = {
  'Chiang Mai': {
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Wat_Phra_That_Doi_Suthep_-_Chiang_Mai.jpg/1280px-Wat_Phra_That_Doi_Suthep_-_Chiang_Mai.jpg',
    landmark: 'Wat Phra That Doi Suthep',
    food: [
      { item: 'Pad Thai (street stall)', price: '$1.50' },
      { item: 'Khao Soi (curry noodle soup)', price: '$2.00' },
      { item: 'Mango sticky rice', price: '$1.00' },
      { item: 'Meal at local restaurant', price: '$3–5' },
      { item: 'Western café meal', price: '$6–9' },
      { item: 'Fine dining entrée', price: '$12–20' },
    ],
    drinks: [
      { item: 'Iced coffee (local café)', price: '$1.00' },
      { item: 'Fresh fruit smoothie', price: '$1.50' },
      { item: 'Local beer (Chang/Leo)', price: '$1.50' },
      { item: 'Craft cocktail at bar', price: '$4–6' },
      { item: 'Boba tea', price: '$2.00' },
    ],
    entertainment: [
      { item: 'Night Bazaar shopping', price: 'Free–$20' },
      { item: 'Thai cooking class (half day)', price: '$25–35' },
      { item: 'Doi Suthep temple entry', price: '$1.00' },
      { item: 'Full-day trekking tour', price: '$25–40' },
      { item: 'Muay Thai class', price: '$8–12' },
      { item: 'Movie theater ticket', price: '$4–6' },
    ],
  },
  'Lisbon': {
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Lisbon_%2836831596786%29_%28cropped%29.jpg/1280px-Lisbon_%2836831596786%29_%28cropped%29.jpg',
    landmark: 'Belém Tower & Tram 28',
    food: [
      { item: 'Pastel de nata (custard tart)', price: '$1.20' },
      { item: 'Bifana sandwich', price: '$3.50' },
      { item: 'Meal at tascas (local tavern)', price: '$8–12' },
      { item: 'Seafood restaurant entrée', price: '$15–25' },
      { item: 'Lunch menu of the day', price: '$7–10' },
      { item: 'Fine dining (Michelin)', price: '$50–80' },
    ],
    drinks: [
      { item: 'Espresso (bica)', price: '$0.80' },
      { item: 'Glass of Vinho Verde', price: '$2.50' },
      { item: 'Craft beer (local)', price: '$3–5' },
      { item: 'Ginjinha (cherry liqueur shot)', price: '$1.50' },
      { item: 'Cocktail at rooftop bar', price: '$8–12' },
    ],
    entertainment: [
      { item: 'Fado show at Alfama', price: '$15–25' },
      { item: 'Tram 28 ride', price: '$3.50' },
      { item: 'Jerónimos Monastery entry', price: '$12' },
      { item: 'Surf lesson at Costa da Caparica', price: '$35–50' },
      { item: 'Day trip to Sintra', price: '$15–25' },
      { item: 'LX Factory market browse', price: 'Free' },
    ],
  },
  'Bali': {
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Tanah-Lot_Bali_Indonesia_Pura-Tanah-Lot-01.jpg/1280px-Tanah-Lot_Bali_Indonesia_Pura-Tanah-Lot-01.jpg',
    landmark: 'Tanah Lot Temple',
    food: [
      { item: 'Nasi Goreng (fried rice)', price: '$1.50–3' },
      { item: 'Babi Guling (suckling pig)', price: '$3–5' },
      { item: 'Warung meal (local)', price: '$2–4' },
      { item: 'Smoothie bowl (Canggu café)', price: '$5–7' },
      { item: 'Western restaurant meal', price: '$8–15' },
      { item: 'Beach club dinner', price: '$20–40' },
    ],
    drinks: [
      { item: 'Bintang beer', price: '$1.50–2' },
      { item: 'Fresh coconut', price: '$1.00' },
      { item: 'Iced latte (café)', price: '$2.50–4' },
      { item: 'Cocktail at beach bar', price: '$5–8' },
      { item: 'Fresh juice', price: '$1.50–3' },
    ],
    entertainment: [
      { item: 'Ubud Monkey Forest entry', price: '$4.50' },
      { item: 'Tegallalang rice terrace', price: '$1.50' },
      { item: 'Surf lesson (2 hrs)', price: '$20–30' },
      { item: 'Full-day scooter rental', price: '$5–7' },
      { item: 'Balinese spa massage (1 hr)', price: '$10–15' },
      { item: 'Uluwatu Kecak fire dance', price: '$7' },
    ],
  },
  'Bangkok': {
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Wat_Arun%2C_Bangkok_%28I%29.jpg/800px-Wat_Arun%2C_Bangkok_%28I%29.jpg',
    landmark: 'Wat Arun (Temple of Dawn)',
    food: [
      { item: 'Street Pad Thai', price: '$1.00–2' },
      { item: 'Som Tam (papaya salad)', price: '$1.00' },
      { item: 'Rice & curry plate', price: '$1.50–2.50' },
      { item: 'Yaowarat (Chinatown) street food', price: '$2–4' },
      { item: 'Mid-range restaurant', price: '$6–12' },
      { item: 'Rooftop restaurant', price: '$25–50' },
    ],
    drinks: [
      { item: 'Thai iced tea', price: '$0.75' },
      { item: 'Chang/Singha beer', price: '$1.50' },
      { item: 'Fresh coconut water', price: '$0.75' },
      { item: 'Rooftop bar cocktail', price: '$8–15' },
      { item: 'Café latte', price: '$2.50–4' },
    ],
    entertainment: [
      { item: 'Grand Palace entry', price: '$16' },
      { item: 'Wat Pho (reclining Buddha)', price: '$7' },
      { item: 'Chatuchak Weekend Market', price: 'Free entry' },
      { item: 'Muay Thai ringside ticket', price: '$30–60' },
      { item: 'River boat day pass (Chao Phraya)', price: '$1–3' },
      { item: 'Thai massage (1 hr)', price: '$6–10' },
    ],
  },
  'Tokyo': {
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Skyscrapers_of_Shinjuku_2009_January.jpg/1280px-Skyscrapers_of_Shinjuku_2009_January.jpg',
    landmark: 'Shinjuku Skyline & Senso-ji Temple',
    food: [
      { item: 'Ramen bowl', price: '$7–10' },
      { item: 'Conveyor belt sushi (10 pcs)', price: '$8–12' },
      { item: 'Onigiri (convenience store)', price: '$1.20' },
      { item: 'Bento box (station)', price: '$5–8' },
      { item: 'Izakaya dinner (per person)', price: '$15–25' },
      { item: 'Omakase sushi (mid-range)', price: '$60–120' },
    ],
    drinks: [
      { item: 'Vending machine coffee', price: '$1.00' },
      { item: 'Draft beer at izakaya', price: '$3–5' },
      { item: 'Sake (glass)', price: '$4–6' },
      { item: 'Café latte (Blue Bottle/etc)', price: '$4–5' },
      { item: 'Highball cocktail', price: '$3–5' },
    ],
    entertainment: [
      { item: 'Senso-ji Temple', price: 'Free' },
      { item: 'Shibuya Sky observation', price: '$15' },
      { item: 'Tsukiji Outer Market food tour', price: '$40–60' },
      { item: 'TeamLab Borderless', price: '$25' },
      { item: 'Onsen day pass', price: '$10–20' },
      { item: 'Karaoke (1 hr per person)', price: '$5–10' },
    ],
  },
  'Barcelona': {
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/80/SF_-_Pair.jpg/800px-SF_-_Pair.jpg',
    landmark: 'Sagrada Família',
    food: [
      { item: 'Patatas bravas (tapas)', price: '$4–6' },
      { item: 'Pintxos (each)', price: '$2–3' },
      { item: 'Menú del día (lunch set)', price: '$10–14' },
      { item: 'Paella for two', price: '$25–40' },
      { item: 'Jamón Ibérico plate', price: '$12–18' },
      { item: 'Fine dining entrée', price: '$30–50' },
    ],
    drinks: [
      { item: 'Café con leche', price: '$1.50–2' },
      { item: 'Glass of cava', price: '$3–5' },
      { item: 'Sangria pitcher', price: '$8–12' },
      { item: 'Caña (small draft beer)', price: '$2–3' },
      { item: 'Cocktail at beach bar', price: '$8–14' },
    ],
    entertainment: [
      { item: 'Sagrada Família ticket', price: '$28' },
      { item: 'Park Güell entry', price: '$12' },
      { item: 'Flamenco show (Tablao)', price: '$30–50' },
      { item: 'Barceloneta beach', price: 'Free' },
      { item: 'Camp Nou stadium tour', price: '$28' },
      { item: 'La Boqueria market browse', price: 'Free' },
    ],
  },
  'Medellín': {
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Medellin_Skyline.jpg/1280px-Medellin_Skyline.jpg',
    landmark: 'Medellín Skyline & Comuna 13',
    food: [
      { item: 'Bandeja Paisa (national dish)', price: '$3–5' },
      { item: 'Arepa con queso', price: '$1.00' },
      { item: 'Empanadas (3 pcs)', price: '$1.00' },
      { item: 'Corrientazo (set lunch)', price: '$2.50–4' },
      { item: 'Mid-range restaurant', price: '$8–15' },
      { item: 'Upscale restaurant dinner', price: '$20–35' },
    ],
    drinks: [
      { item: 'Tinto (black coffee)', price: '$0.30' },
      { item: 'Fresh fruit juice (natural)', price: '$1.00' },
      { item: 'Aguardiente shot', price: '$0.75' },
      { item: 'Club Colombia beer', price: '$1.00–2' },
      { item: 'Craft cocktail', price: '$4–7' },
    ],
    entertainment: [
      { item: 'Comuna 13 graffiti tour', price: '$10–15' },
      { item: 'Metrocable ride (one way)', price: '$0.75' },
      { item: 'Botanical Garden entry', price: 'Free' },
      { item: 'Paragliding', price: '$40–60' },
      { item: 'Guatapé day trip (inc. El Peñón)', price: '$20–30' },
      { item: 'Salsa class', price: '$5–10' },
    ],
  },
  'Dubai': {
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Dubai_Marina_Skyline.jpg/1280px-Dubai_Marina_Skyline.jpg',
    landmark: 'Burj Khalifa & Dubai Marina',
    food: [
      { item: 'Shawarma wrap (street)', price: '$2–3' },
      { item: 'Karak chai', price: '$1.00' },
      { item: 'Al Machboos rice platter', price: '$5–8' },
      { item: 'Food court meal (mall)', price: '$7–12' },
      { item: 'Mid-range restaurant', price: '$20–35' },
      { item: 'Fine dining (Burj)', price: '$80–200' },
    ],
    drinks: [
      { item: 'Fresh juice (mango/orange)', price: '$2–3' },
      { item: 'Arabic coffee (qahwa)', price: '$2–4' },
      { item: 'Beer at licensed venue', price: '$10–14' },
      { item: 'Cocktail at sky bar', price: '$18–30' },
      { item: 'Café latte (specialty)', price: '$5–7' },
    ],
    entertainment: [
      { item: 'Burj Khalifa observation deck', price: '$40–55' },
      { item: 'Dubai Mall (inc. aquarium)', price: '$35' },
      { item: 'Desert safari (half day)', price: '$40–70' },
      { item: 'Dubai Frame entry', price: '$14' },
      { item: 'Dhow dinner cruise', price: '$30–60' },
      { item: 'Museum of the Future', price: '$40' },
    ],
  },
};

export const DESTINATIONS: Destination[] = [
  { id: 'chiangmai', city: 'Chiang Mai', country: 'Thailand', emoji: '🏔️', lat: 18.7883, lng: 98.9853, rating: 4.8, pop: '7M+ nomads', wikiTitle: 'Chiang Mai', speed: 52, safetyScore: 8.2, monthlyCost: 1200, weatherDesc: 'Warm & Sunny', temp: 28, tags: ['Affordable', 'Digital Nomad'], popular: true, desc: 'Ancient temples, cool mountains, fast internet, and the most affordable nomad lifestyle in Asia.' },
  { id: 'lisbon', city: 'Lisbon', country: 'Portugal', emoji: '🇵🇹', lat: 38.7169, lng: -9.1399, rating: 4.7, pop: '6M+ nomads', wikiTitle: 'Lisbon', speed: 48, safetyScore: 8.7, monthlyCost: 1605, weatherDesc: 'Mild & Breezy', temp: 18, tags: ['Bitcoin-Friendly', 'Tax Perks'], popular: true, desc: 'Sunny capital with pastel streets, great food, crypto-friendly culture, and NHR tax regime.' },
  { id: 'bali', city: 'Bali', country: 'Indonesia', emoji: '🌴', lat: -8.3405, lng: 115.0919, rating: 4.8, pop: '8M+ nomads', wikiTitle: 'Bali', speed: 38, safetyScore: 7.9, monthlyCost: 1400, weatherDesc: 'Tropical & Lush', temp: 30, tags: ['Surf & Co-Work', 'Nomad Hub'], popular: true, desc: 'Tropical paradise with rice terraces, temples, and a world-class digital nomad community in Canggu.' },
  { id: 'bangkok', city: 'Bangkok', country: 'Thailand', emoji: '🛕', lat: 13.7563, lng: 100.5018, rating: 4.7, pop: '11M+ nomads', wikiTitle: 'Bangkok', speed: 45, safetyScore: 7.5, monthlyCost: 1100, weatherDesc: 'Hot & Vibrant', temp: 32, tags: ['Street Food', 'Nightlife'], popular: true, desc: 'Vibrant street food, temples, and a booming nomad scene. Low cost of living with fast fiber internet.' },
  { id: 'tokyo', city: 'Tokyo', country: 'Japan', emoji: '🗼', lat: 35.6762, lng: 139.6503, rating: 4.9, pop: '14M+ nomads', wikiTitle: 'Tokyo', speed: 78, safetyScore: 9.4, monthlyCost: 2800, weatherDesc: 'Cool & Clear', temp: 16, tags: ['BTC Friendly', 'Ultra-Modern'], popular: false, desc: 'Ultra-modern city with ancient temples, perfect transit, and incredible food. Bitcoin-friendly with thousands of merchants.' },
  { id: 'barcelona', city: 'Barcelona', country: 'Spain', emoji: '🏖️', lat: 41.3851, lng: 2.1734, rating: 4.8, pop: '7M+ nomads', wikiTitle: 'Barcelona', speed: 55, safetyScore: 7.8, monthlyCost: 2200, weatherDesc: 'Sunny & Warm', temp: 22, tags: ['Beach Life', 'Startup Hub'], popular: false, desc: "Architecture, beaches, and an incredible startup scene. One of Europe's top Bitcoin cities." },
  { id: 'medellin', city: 'Medellín', country: 'Colombia', emoji: '🌺', lat: 6.2476, lng: -75.5658, rating: 4.6, pop: '5M+ nomads', wikiTitle: 'Medellín', speed: 32, safetyScore: 6.8, monthlyCost: 900, weatherDesc: 'Spring All Year', temp: 22, tags: ['Budget Pick', 'Crypto Scene'], popular: false, desc: 'The city of eternal spring. Growing crypto scene, affordable living, and a welcoming local culture.' },
  { id: 'dubai', city: 'Dubai', country: 'UAE', emoji: '🏙️', lat: 25.2048, lng: 55.2708, rating: 4.7, pop: '9M+ nomads', wikiTitle: 'Dubai', speed: 62, safetyScore: 8.9, monthlyCost: 3200, weatherDesc: 'Sunny & Hot', temp: 35, tags: ['Tax-Free', 'Luxury'], popular: false, desc: 'Tax-free hub with world-class infrastructure, crypto-friendly regulations, and 0% income tax.' },
];

const getHour = () => new Date().getHours();

export const getCategories = (): PlaceCategory[] => [
  { id: 'food', label: 'Food', emoji: getHour() < 10 ? '🍳' : getHour() < 15 ? '🍜' : getHour() < 20 ? '🍽️' : '🌮', query: 'restaurants' },
  { id: 'cafe', label: 'Cafes', emoji: getHour() < 11 ? '☕' : getHour() < 16 ? '🧋' : '🍵', query: 'cafes' },
  { id: 'drinks', label: 'Drinks', emoji: '🍸', query: 'bars lounges' },
  { id: 'hotel', label: 'Hotels', emoji: '🏨', query: 'hotels' },
  { id: 'shop', label: 'Shopping', emoji: '🛍️', query: 'shopping' },
  { id: 'transport', label: 'Transit', emoji: '🚇', query: 'public transit' },
  { id: 'gym', label: 'Fitness', emoji: '💪', query: 'gym' },
  { id: 'beach', label: 'Beaches', emoji: '🏖️', query: 'beach' },
  { id: 'nightlife', label: 'Nightlife', emoji: '🎵', query: 'nightlife bars' },
  { id: 'attractions', label: 'Attractions', emoji: '🎡', query: 'tourist attractions things to do' },
  { id: 'atm', label: 'ATM', emoji: '🏧', query: 'atm cash machine' },
  { id: 'btcatm', label: 'BTC ATM', emoji: '₿', query: 'bitcoin atm cryptocurrency' },
  { id: 'hospital', label: 'Medical', emoji: '🏥', query: 'hospital' },
  { id: 'pharmacy', label: 'Pharmacy', emoji: '💊', query: 'pharmacy' },
  { id: 'auto', label: 'Auto Care', emoji: '🔧', query: 'auto repair car maintenance' },
  { id: 'gas', label: 'Gas Stations', emoji: '⛽', query: 'gas station fuel' },
  { id: 'laundry', label: 'Laundry', emoji: '🧺', query: 'laundromat laundry service' },
  { id: 'coworking', label: 'Coworking', emoji: '💻', query: 'coworking space shared office' },
  { id: 'spa', label: 'Spa & Beauty', emoji: '💆', query: 'spa beauty salon massage' },
  { id: 'ev', label: 'EV Charging', emoji: '⚡', query: 'electric vehicle charging station' },
];

export const CATEGORY_SUBS: Record<string, SubCategory[]> = {
  food: [
    { label: 'American', query: 'american restaurant', emoji: '🍔' },
    { label: 'Bakery', query: 'bakery bread', emoji: '🥐' },
    { label: 'Bar & Grill', query: 'bar grill', emoji: '🍺' },
    { label: 'Burger', query: 'burger restaurant', emoji: '🍔' },
    { label: 'Chinese', query: 'chinese restaurant', emoji: '🥡' },
    { label: 'Fast Food', query: 'fast food', emoji: '🍟' },
    { label: 'Italian', query: 'italian restaurant', emoji: '🍝' },
    { label: 'Japanese', query: 'japanese restaurant', emoji: '🍱' },
    { label: 'Mexican', query: 'mexican restaurant', emoji: '🌮' },
    { label: 'Pizza', query: 'pizza restaurant', emoji: '🍕' },
    { label: 'Seafood', query: 'seafood restaurant', emoji: '🦞' },
    { label: 'Thai', query: 'thai restaurant', emoji: '🍜' },
    { label: 'Vietnamese', query: 'vietnamese restaurant', emoji: '🍲' },
    { label: 'Steak', query: 'steakhouse', emoji: '🥩' },
    { label: 'All Food', query: 'restaurants', emoji: '🍽️' },
  ],
  cafe: [
    { label: 'Coffee', query: 'coffee cafe', emoji: '☕' },
    { label: 'Boba / Tea', query: 'boba tea shop', emoji: '🧋' },
    { label: 'Coworking', query: 'coworking cafe wifi', emoji: '💻' },
    { label: 'Bakery Café', query: 'bakery cafe', emoji: '🥐' },
    { label: 'Juice Bar', query: 'juice bar smoothie', emoji: '🧃' },
    { label: 'All Cafes', query: 'cafes', emoji: '🍵' },
  ],
  drinks: [
    { label: 'Cocktail Bar', query: 'cocktail bar lounge', emoji: '🍸' },
    { label: 'Brewery', query: 'brewery craft beer taproom', emoji: '🍺' },
    { label: 'Wine Bar', query: 'wine bar', emoji: '🍷' },
    { label: 'Lounge', query: 'lounge bar chill', emoji: '🛋️' },
    { label: 'Sports Bar', query: 'sports bar pub', emoji: '📺' },
    { label: 'Rooftop Bar', query: 'rooftop bar', emoji: '🌃' },
    { label: 'Hookah', query: 'hookah lounge shisha', emoji: '💨' },
    { label: 'All Bars', query: 'bars lounges', emoji: '🥂' },
  ],
  shop: [
    { label: 'Mall', query: 'shopping mall', emoji: '🏬' },
    { label: 'Grocery', query: 'supermarket grocery', emoji: '🛒' },
    { label: 'Electronics', query: 'electronics store', emoji: '📱' },
    { label: 'Clothing', query: 'clothing store fashion', emoji: '👔' },
    { label: 'Market', query: 'local market bazaar', emoji: '🏪' },
    { label: 'All Shops', query: 'shopping', emoji: '🛍️' },
  ],
  nightlife: [
    { label: 'Bar', query: 'bar cocktail lounge', emoji: '🍸' },
    { label: 'Nightclub', query: 'nightclub dance', emoji: '🎉' },
    { label: 'Live Music', query: 'live music venue', emoji: '🎵' },
    { label: 'Rooftop', query: 'rooftop bar', emoji: '🌃' },
    { label: 'Pub', query: 'pub sports bar', emoji: '🍺' },
    { label: 'Brewery', query: 'brewery taproom', emoji: '🍻' },
  ],
  hotel: [
    { label: 'Hotel', query: 'hotel', emoji: '🏨' },
    { label: 'Hostel', query: 'hostel backpacker', emoji: '🛏️' },
    { label: 'Airbnb', query: 'vacation rental', emoji: '🏠' },
    { label: 'Resort', query: 'resort luxury', emoji: '🏖️' },
    { label: 'Boutique', query: 'boutique hotel', emoji: '🌟' },
  ],
  transport: [
    { label: 'Bus', query: 'bus station stop', emoji: '🚌' },
    { label: 'Train / MRT', query: 'train station metro', emoji: '🚇' },
    { label: 'Airport', query: 'airport', emoji: '✈️' },
    { label: 'Taxi / Grab', query: 'taxi grab ride share', emoji: '🚕' },
    { label: 'Ferry', query: 'ferry boat terminal', emoji: '⛴️' },
    { label: 'Bike Share', query: 'bike rental bicycle', emoji: '🚲' },
  ],
  gym: [
    { label: 'Gym', query: 'gym fitness center', emoji: '💪' },
    { label: 'Yoga', query: 'yoga studio', emoji: '🧘' },
    { label: 'Swimming', query: 'swimming pool', emoji: '🏊' },
    { label: 'Muay Thai', query: 'muay thai boxing gym', emoji: '🥊' },
    { label: 'Rock Climb', query: 'rock climbing gym', emoji: '🧗' },
  ],
  auto: [
    { label: 'Oil Change', query: 'oil change auto service', emoji: '🛢️' },
    { label: 'Tire Shop', query: 'tire shop tire service', emoji: '🛞' },
    { label: 'Body Shop', query: 'auto body shop collision repair', emoji: '🚗' },
    { label: 'Mechanic', query: 'auto mechanic car repair', emoji: '🔧' },
    { label: 'Car Wash', query: 'car wash detailing', emoji: '🧽' },
    { label: 'Brakes', query: 'brake repair service', emoji: '🛑' },
    { label: 'Transmission', query: 'transmission repair service', emoji: '⚙️' },
    { label: 'Towing', query: 'towing service roadside assistance', emoji: '🚛' },
    { label: 'All Auto', query: 'auto repair car maintenance', emoji: '🔧' },
  ],
  beach: [
    { label: 'Beach', query: 'beach ocean swimming', emoji: '🏖️' },
    { label: 'Park', query: 'park garden', emoji: '🌳' },
    { label: 'Lake', query: 'lake waterfront', emoji: '🏞️' },
    { label: 'Hiking', query: 'hiking trail nature', emoji: '🥾' },
  ],
  attractions: [
    { label: 'Museums', query: 'museum art gallery', emoji: '🏛️' },
    { label: 'Tours', query: 'sightseeing tour', emoji: '🗺️' },
    { label: 'Theme Parks', query: 'theme park amusement', emoji: '🎢' },
    { label: 'Landmarks', query: 'landmark monument', emoji: '🗽' },
    { label: 'Events', query: 'events concerts festivals', emoji: '🎪' },
  ],
};

export const PHRASES: Record<string, { label: string; phrases: { en: string; local: string; phon: string }[] }> = {
  es: { label: '🇪🇸 Spanish', phrases: [
    { en: 'Hello', local: 'Hola', phon: 'OH-lah' },
    { en: 'Goodbye', local: 'Adiós', phon: 'ah-dee-OHS' },
    { en: 'Please', local: 'Por favor', phon: 'por fah-VOR' },
    { en: 'Thank you', local: 'Gracias', phon: 'GRAH-syahs' },
    { en: 'Yes / No', local: 'Sí / No', phon: 'see / noh' },
    { en: 'Excuse me', local: 'Disculpe', phon: 'dees-KOOL-peh' },
    { en: 'I don\'t understand', local: 'No entiendo', phon: 'noh en-tee-EN-doh' },
    { en: 'Do you speak English?', local: '¿Habla inglés?', phon: 'AH-blah een-GLES' },
    { en: 'Where is…?', local: '¿Dónde está…?', phon: 'DON-day es-TAH' },
    { en: 'Where is the bathroom?', local: '¿Dónde está el baño?', phon: 'DON-day es-TAH el BAH-nyoh' },
    { en: 'Where is the airport?', local: '¿Dónde está el aeropuerto?', phon: 'DON-day es-TAH el ah-eh-roh-PWER-toh' },
    { en: 'How much does this cost?', local: '¿Cuánto cuesta?', phon: 'KWAHN-toh KWES-tah' },
    { en: 'I need a taxi', local: 'Necesito un taxi', phon: 'neh-seh-SEE-toh oon TAK-see' },
    { en: 'I need a doctor', local: 'Necesito un médico', phon: 'neh-seh-SEE-toh oon MEH-dee-koh' },
    { en: 'Help!', local: '¡Ayuda!', phon: 'ah-YOO-dah' },
    { en: 'Water', local: 'Agua', phon: 'AH-gwah' },
    { en: 'The check, please', local: 'La cuenta, por favor', phon: 'lah KWEN-tah por fah-VOR' },
    { en: 'Left / Right / Straight', local: 'Izquierda / Derecha / Recto', phon: 'ees-kee-ER-dah / deh-REH-chah / REK-toh' },
    { en: 'I\'m lost', local: 'Estoy perdido/a', phon: 'es-TOY per-DEE-doh' },
    { en: 'Can you help me?', local: '¿Puede ayudarme?', phon: 'PWEH-deh ah-yoo-DAR-meh' },
    { en: 'Do you accept Bitcoin?', local: '¿Acepta Bitcoin?', phon: 'ah-SEP-tah Bitcoin' },
    { en: 'Good morning', local: 'Buenos días', phon: 'BWEH-nohs DEE-ahs' },
  ]},
  zh: { label: '🇨🇳 Mandarin', phrases: [
    { en: 'Hello', local: '你好', phon: 'nee-HOW' },
    { en: 'Goodbye', local: '再见', phon: 'zai-jee-EN' },
    { en: 'Please', local: '请', phon: 'ching' },
    { en: 'Thank you', local: '谢谢', phon: 'shyeh-shyeh' },
    { en: 'Yes / No', local: '是 / 不是', phon: 'shir / boo-shir' },
    { en: 'Excuse me', local: '请问', phon: 'ching-wen' },
    { en: 'I don\'t understand', local: '我不明白', phon: 'woh boo ming-bai' },
    { en: 'Do you speak English?', local: '你会说英语吗？', phon: 'nee hway shwoh ying-yoo mah' },
    { en: 'Where is…?', local: '…在哪里？', phon: '...zai nah-lee' },
    { en: 'Where is the bathroom?', local: '洗手间在哪里？', phon: 'shee-show-jee-en zai nah-lee' },
    { en: 'Where is the airport?', local: '机场在哪里？', phon: 'jee-chahng zai nah-lee' },
    { en: 'How much does this cost?', local: '这个多少钱？', phon: 'jeh-guh dwoh-shaow chee-en' },
    { en: 'I need a taxi', local: '我需要出租车', phon: 'woh shoo-yaow choo-zoo-chuh' },
    { en: 'I need a doctor', local: '我需要医生', phon: 'woh shoo-yaow ee-sheng' },
    { en: 'Help!', local: '救命！', phon: 'jyo-ming' },
    { en: 'Water', local: '水', phon: 'shway' },
    { en: 'The check, please', local: '买单', phon: 'mai-dahn' },
    { en: 'Left / Right / Straight', local: '左 / 右 / 直走', phon: 'zwoh / yo / jr-zoh' },
    { en: 'I\'m lost', local: '我迷路了', phon: 'woh mee-loo luh' },
    { en: 'Can you help me?', local: '你能帮我吗？', phon: 'nee nung bahng woh mah' },
  ]},
  fr: { label: '🇫🇷 French', phrases: [
    { en: 'Hello', local: 'Bonjour', phon: 'bohn-ZHOOR' },
    { en: 'Goodbye', local: 'Au revoir', phon: 'oh reh-VWAHR' },
    { en: 'Please', local: 'S\'il vous plaît', phon: 'seel voo PLAY' },
    { en: 'Thank you', local: 'Merci', phon: 'mehr-SEE' },
    { en: 'Yes / No', local: 'Oui / Non', phon: 'wee / nohn' },
    { en: 'Excuse me', local: 'Excusez-moi', phon: 'ex-koo-ZAY mwah' },
    { en: 'I don\'t understand', local: 'Je ne comprends pas', phon: 'zhuh nuh kohm-PRAHN pah' },
    { en: 'Do you speak English?', local: 'Parlez-vous anglais?', phon: 'par-LAY voo ahn-GLAY' },
    { en: 'Where is…?', local: 'Où est…?', phon: 'oo AY' },
    { en: 'Where is the bathroom?', local: 'Où sont les toilettes?', phon: 'oo sohn lay twa-LET' },
    { en: 'Where is the airport?', local: "Où est l'aéroport?", phon: 'oo AY lay-ro-POUR' },
    { en: 'How much does this cost?', local: 'Combien ça coûte?', phon: 'kohm-BYEH sah KOOT' },
    { en: 'I need a taxi', local: 'J\'ai besoin d\'un taxi', phon: 'zhay buh-ZWEH dun TAK-see' },
    { en: 'I need a doctor', local: 'J\'ai besoin d\'un médecin', phon: 'zhay buh-ZWEH dun med-SAN' },
    { en: 'Help!', local: 'Au secours!', phon: 'oh skoor' },
    { en: 'Water', local: 'De l\'eau', phon: 'duh LOH' },
    { en: 'The check, please', local: 'L\'addition, s\'il vous plaît', phon: 'lah-dee-SYOHN seel voo PLAY' },
    { en: 'Left / Right / Straight', local: 'Gauche / Droite / Tout droit', phon: 'gohsh / drwaht / too DRWAH' },
    { en: 'I\'m lost', local: 'Je suis perdu(e)', phon: 'zhuh swee pair-DOO' },
    { en: 'Can you help me?', local: 'Pouvez-vous m\'aider?', phon: 'poo-VAY voo may-DAY' },
    { en: 'Do you accept Bitcoin?', local: 'Acceptez-vous Bitcoin?', phon: 'ak-sep-TAY voo Bitcoin' },
  ]},
  ar: { label: '🇸🇦 Arabic', phrases: [
    { en: 'Hello', local: 'مرحبا', phon: 'MAR-ha-ba' },
    { en: 'Goodbye', local: 'مع السلامة', phon: 'ma-ah sa-LAH-mah' },
    { en: 'Please', local: 'من فضلك', phon: 'min FAD-lak' },
    { en: 'Thank you', local: 'شكراً', phon: 'SHOOK-ran' },
    { en: 'Yes / No', local: 'نعم / لا', phon: 'NA-am / lah' },
    { en: 'Excuse me', local: 'عفواً', phon: 'AF-wan' },
    { en: 'I don\'t understand', local: 'لا أفهم', phon: 'lah AF-ham' },
    { en: 'Do you speak English?', local: 'هل تتكلم الإنجليزية؟', phon: 'hal ta-ta-KAL-lam al-in-glee-ZEE-ya' },
    { en: 'Where is…?', local: 'أين…؟', phon: 'AY-na' },
    { en: 'Where is the bathroom?', local: 'أين الحمام؟', phon: 'AY-na al-ham-MAHM' },
    { en: 'Where is the airport?', local: 'أين المطار؟', phon: 'AY-na al-ma-TAHR' },
    { en: 'How much does this cost?', local: 'بكم هذا؟', phon: 'bi-KAM HAH-tha' },
    { en: 'I need a taxi', local: 'أحتاج تاكسي', phon: 'ah-TAHJ TAK-see' },
    { en: 'I need a doctor', local: 'أحتاج طبيب', phon: 'ah-TAHJ ta-BEEB' },
    { en: 'Help!', local: '!مساعدة', phon: 'moo-SAH-ah-dah' },
    { en: 'Water', local: 'ماء', phon: 'MAH' },
    { en: 'The check, please', local: 'الحساب من فضلك', phon: 'al-hee-SAHB min FAD-lak' },
    { en: 'Left / Right / Straight', local: 'يسار / يمين / مستقيم', phon: 'ya-SAHR / ya-MEEN / mus-ta-QEEM' },
    { en: 'I\'m lost', local: 'أنا ضائع', phon: 'AH-na DAH-ee' },
    { en: 'Can you help me?', local: 'هل يمكنك مساعدتي؟', phon: 'hal yum-ki-nak moo-SAH-ah-da-tee' },
  ]},
  hi: { label: '🇮🇳 Hindi', phrases: [
    { en: 'Hello', local: 'नमस्ते', phon: 'nah-mah-STAY' },
    { en: 'Goodbye', local: 'अलविदा', phon: 'al-vee-DAH' },
    { en: 'Please', local: 'कृपया', phon: 'KRIP-yah' },
    { en: 'Thank you', local: 'धन्यवाद', phon: 'dhun-yah-VAHD' },
    { en: 'Yes / No', local: 'हाँ / नहीं', phon: 'hahn / nah-HEE' },
    { en: 'Excuse me', local: 'माफ़ कीजिए', phon: 'MAHF kee-jee-ay' },
    { en: 'I don\'t understand', local: 'मुझे समझ नहीं आया', phon: 'MOO-jhay sa-MAHJ nah-HEE AH-yah' },
    { en: 'Do you speak English?', local: 'क्या आप अंग्रेज़ी बोलते हैं?', phon: 'kyah aap ANG-reh-zee BOL-tay hain' },
    { en: 'Where is…?', local: '…कहाँ है?', phon: '...ka-HAHN hai' },
    { en: 'Where is the bathroom?', local: 'बाथरूम कहाँ है?', phon: 'BATH-room ka-HAHN hai' },
    { en: 'Where is the airport?', local: 'हवाई अड्डा कहाँ है?', phon: 'ha-VAH-ee ADD-dah ka-HAHN hai' },
    { en: 'How much does this cost?', local: 'यह कितने का है?', phon: 'yeh KIT-nay kah hai' },
    { en: 'I need a taxi', local: 'मुझे टैक्सी चाहिए', phon: 'MOO-jhay TAK-see CHAH-hee-ay' },
    { en: 'I need a doctor', local: 'मुझे डॉक्टर चाहिए', phon: 'MOO-jhay DOK-tar CHAH-hee-ay' },
    { en: 'Help!', local: 'मदद!', phon: 'MAH-dahd' },
    { en: 'Water', local: 'पानी', phon: 'PAH-nee' },
    { en: 'The check, please', local: 'बिल दीजिए', phon: 'bill DEE-jee-ay' },
    { en: 'Left / Right / Straight', local: 'बाएँ / दाएँ / सीधा', phon: 'BAH-ay / DAH-ay / SEE-dhah' },
    { en: 'I\'m lost', local: 'मैं खो गया/गयी हूँ', phon: 'main KHO gah-YAH hoon' },
    { en: 'Can you help me?', local: 'क्या आप मेरी मदद कर सकते हैं?', phon: 'kyah aap MEH-ree MAH-dahd kar SAK-tay hain' },
  ]},
  pt: { label: '🇧🇷 Portuguese', phrases: [
    { en: 'Hello', local: 'Olá', phon: 'oh-LAH' },
    { en: 'Goodbye', local: 'Tchau', phon: 'CHOW' },
    { en: 'Please', local: 'Por favor', phon: 'por fah-VOR' },
    { en: 'Thank you', local: 'Obrigado / Obrigada', phon: 'oh-bree-GAH-doo' },
    { en: 'Yes / No', local: 'Sim / Não', phon: 'seem / now' },
    { en: 'Excuse me', local: 'Com licença', phon: 'kohm lee-SEN-sah' },
    { en: 'I don\'t understand', local: 'Não entendo', phon: 'now en-TEN-doo' },
    { en: 'Do you speak English?', local: 'Você fala inglês?', phon: 'voh-SAY FAH-lah een-GLES' },
    { en: 'Where is…?', local: 'Onde fica…?', phon: 'ON-jee FEE-kah' },
    { en: 'Where is the bathroom?', local: 'Onde fica o banheiro?', phon: 'ON-jee FEE-kah oh ban-YAY-roo' },
    { en: 'Where is the airport?', local: 'Onde fica o aeroporto?', phon: 'ON-jee FEE-kah oh ah-eh-roh-POR-too' },
    { en: 'How much does this cost?', local: 'Quanto custa?', phon: 'KWAHN-too KOO-stah' },
    { en: 'I need a taxi', local: 'Preciso de um táxi', phon: 'preh-SEE-zoo jee oong TAK-see' },
    { en: 'I need a doctor', local: 'Preciso de um médico', phon: 'preh-SEE-zoo jee oong MEH-jee-koo' },
    { en: 'Help!', local: 'Socorro!', phon: 'so-KOH-hoo' },
    { en: 'Water', local: 'Água', phon: 'AH-gwah' },
    { en: 'The check, please', local: 'A conta, por favor', phon: 'ah KOHN-tah por fah-VOR' },
    { en: 'Left / Right / Straight', local: 'Esquerda / Direita / Em frente', phon: 'esh-KEHR-dah / jee-RAY-tah / en FREN-chee' },
    { en: 'I\'m lost', local: 'Estou perdido/a', phon: 'es-TOH per-JEE-doo' },
    { en: 'Can you help me?', local: 'Pode me ajudar?', phon: 'POH-jee mee ah-zhoo-DAR' },
    { en: 'Do you accept Bitcoin?', local: 'Aceita Bitcoin?', phon: 'ah-SAY-ta Bitcoin' },
  ]},
  ja: { label: '🇯🇵 Japanese', phrases: [
    { en: 'Hello', local: 'こんにちは', phon: 'kon-nee-chee-wa' },
    { en: 'Goodbye', local: 'さようなら', phon: 'sah-yoh-nah-rah' },
    { en: 'Please', local: 'お願いします', phon: 'oh-neh-gai shee-mas' },
    { en: 'Thank you', local: 'ありがとうございます', phon: 'a-ree-ga-toh go-zai-mas' },
    { en: 'Yes / No', local: 'はい / いいえ', phon: 'hai / ee-eh' },
    { en: 'Excuse me', local: 'すみません', phon: 'soo-mee-mah-sen' },
    { en: 'I don\'t understand', local: 'わかりません', phon: 'wah-ka-ree-mah-sen' },
    { en: 'Do you speak English?', local: '英語を話せますか？', phon: 'AY-go oh ha-nah-seh-mas-ka' },
    { en: 'Where is…?', local: '…はどこですか？', phon: '...wa do-ko des-ka' },
    { en: 'Where is the bathroom?', local: 'トイレはどこですか？', phon: 'TOY-reh wa do-ko des-ka' },
    { en: 'Where is the airport?', local: '空港はどこですか？', phon: 'koo-koh wa do-ko des-ka' },
    { en: 'How much does this cost?', local: 'いくらですか？', phon: 'ee-koo-ra des-ka' },
    { en: 'I need a taxi', local: 'タクシーをお願いします', phon: 'TAK-shee oh oh-neh-gai shee-mas' },
    { en: 'I need a doctor', local: '医者が必要です', phon: 'ee-sha ga hee-tsu-yo des' },
    { en: 'Help!', local: '助けて！', phon: 'ta-soo-ke-te' },
    { en: 'Water', local: '水', phon: 'mee-zoo' },
    { en: 'The check, please', local: 'お会計お願いします', phon: 'oh-kai-kay oh-neh-gai shee-mas' },
    { en: 'Left / Right / Straight', local: '左 / 右 / まっすぐ', phon: 'hee-da-ree / mee-gee / mas-soo-goo' },
    { en: 'I\'m lost', local: '道に迷いました', phon: 'mee-chee nee mah-yoy-mah-shta' },
    { en: 'Can you help me?', local: '助けてもらえますか？', phon: 'ta-soo-ke-te mo-rah-eh-mas-ka' },
    { en: 'Do you accept Bitcoin?', local: 'ビットコインは使えますか？', phon: 'bit-to-ko-in wa tsoo-ka-e-mas-ka' },
  ]},
  de: { label: '🇩🇪 German', phrases: [
    { en: 'Hello', local: 'Hallo', phon: 'HAL-oh' },
    { en: 'Goodbye', local: 'Auf Wiedersehen', phon: 'owf VEE-der-zay-en' },
    { en: 'Please', local: 'Bitte', phon: 'BIT-teh' },
    { en: 'Thank you', local: 'Danke schön', phon: 'DAHN-keh shern' },
    { en: 'Yes / No', local: 'Ja / Nein', phon: 'yah / nine' },
    { en: 'Excuse me', local: 'Entschuldigung', phon: 'ent-SHOOL-dee-goong' },
    { en: 'I don\'t understand', local: 'Ich verstehe nicht', phon: 'ikh fer-SHTAY-eh nikht' },
    { en: 'Do you speak English?', local: 'Sprechen Sie Englisch?', phon: 'SHPRE-khen zee ENG-lish' },
    { en: 'Where is…?', local: 'Wo ist…?', phon: 'voh ist' },
    { en: 'Where is the bathroom?', local: 'Wo ist die Toilette?', phon: 'voh ist dee twa-LET-teh' },
    { en: 'Where is the airport?', local: 'Wo ist der Flughafen?', phon: 'voh ist dair FLOOK-hah-fen' },
    { en: 'How much does this cost?', local: 'Wie viel kostet das?', phon: 'vee feel KOS-tet dahs' },
    { en: 'I need a taxi', local: 'Ich brauche ein Taxi', phon: 'ikh BROW-kheh ayn TAK-see' },
    { en: 'I need a doctor', local: 'Ich brauche einen Arzt', phon: 'ikh BROW-kheh eye-nen artst' },
    { en: 'Help!', local: 'Hilfe!', phon: 'HIL-feh' },
    { en: 'Water', local: 'Wasser', phon: 'VAH-ser' },
    { en: 'The check, please', local: 'Die Rechnung, bitte', phon: 'dee REKH-noong BIT-teh' },
    { en: 'Left / Right / Straight', local: 'Links / Rechts / Geradeaus', phon: 'links / rekhts / geh-RAH-deh-ows' },
    { en: 'I\'m lost', local: 'Ich habe mich verlaufen', phon: 'ikh HAH-beh mikh fer-LOW-fen' },
    { en: 'Can you help me?', local: 'Können Sie mir helfen?', phon: 'KER-nen zee meer HEL-fen' },
    { en: 'Do you accept Bitcoin?', local: 'Nehmen Sie Bitcoin?', phon: 'NAY-men zee Bitcoin' },
  ]},
  ko: { label: '🇰🇷 Korean', phrases: [
    { en: 'Hello', local: '안녕하세요', phon: 'ahn-nyeong-ha-SE-yo' },
    { en: 'Goodbye', local: '안녕히 가세요', phon: 'ahn-nyeong-hee ga-SE-yo' },
    { en: 'Please', local: '주세요', phon: 'joo-SE-yo' },
    { en: 'Thank you', local: '감사합니다', phon: 'gam-sa-HAM-ni-da' },
    { en: 'Yes / No', local: '네 / 아니요', phon: 'neh / ah-nee-yo' },
    { en: 'Excuse me', local: '실례합니다', phon: 'shil-lye-HAM-ni-da' },
    { en: 'I don\'t understand', local: '이해 못 해요', phon: 'ee-HAY moht HAY-yo' },
    { en: 'Do you speak English?', local: '영어 하세요?', phon: 'YUNG-uh ha-SE-yo' },
    { en: 'Where is…?', local: '…어디에요?', phon: '...uh-dee-AY-yo' },
    { en: 'Where is the bathroom?', local: '화장실 어디에요?', phon: 'hwa-jang-SHIL uh-dee-AY-yo' },
    { en: 'Where is the airport?', local: '공항 어디에요?', phon: 'gong-HANG uh-dee-AY-yo' },
    { en: 'How much does this cost?', local: '이거 얼마예요?', phon: 'ee-guh UHL-ma-YE-yo' },
    { en: 'I need a taxi', local: '택시 불러주세요', phon: 'TEK-shee bool-luh-joo-SE-yo' },
    { en: 'I need a doctor', local: '의사가 필요해요', phon: 'ee-sa-ga PIL-yo-HAY-yo' },
    { en: 'Help!', local: '도와주세요!', phon: 'do-wa-joo-SE-yo' },
    { en: 'Water', local: '물', phon: 'mool' },
    { en: 'The check, please', local: '계산서 주세요', phon: 'gye-san-SUH joo-SE-yo' },
    { en: 'Left / Right / Straight', local: '왼쪽 / 오른쪽 / 직진', phon: 'wen-JJOK / oh-run-JJOK / jik-JIN' },
    { en: 'I\'m lost', local: '길을 잃었어요', phon: 'GHEE-rool ee-ruh-ssuh-yo' },
    { en: 'Can you help me?', local: '도와주실 수 있어요?', phon: 'do-wa-joo-SHIL soo ee-ssuh-yo' },
  ]},
  th: { label: '🇹🇭 Thai', phrases: [
    { en: 'Hello', local: 'สวัสดี', phon: 'sa-wat-DEE' },
    { en: 'Goodbye', local: 'ลาก่อน', phon: 'lah-GORN' },
    { en: 'Please', local: 'กรุณา', phon: 'ga-roo-NAH' },
    { en: 'Thank you', local: 'ขอบคุณ', phon: 'khop KHUN' },
    { en: 'Yes / No', local: 'ใช่ / ไม่ใช่', phon: 'chai / mai-chai' },
    { en: 'Excuse me', local: 'ขอโทษ', phon: 'khor-TOHT' },
    { en: 'I don\'t understand', local: 'ไม่เข้าใจ', phon: 'mai khao-JAI' },
    { en: 'Do you speak English?', local: 'คุณพูดภาษาอังกฤษได้ไหม?', phon: 'khun POOT pah-SAH ang-GRIT dai mai' },
    { en: 'Where is…?', local: '…อยู่ที่ไหน?', phon: '...yoo tee NAI' },
    { en: 'Where is the bathroom?', local: 'ห้องน้ำอยู่ที่ไหน?', phon: 'hong-NAHM yoo tee NAI' },
    { en: 'Where is the airport?', local: 'สนามบินอยู่ที่ไหน?', phon: 'sa-NAHM bin yoo tee NAI' },
    { en: 'How much does this cost?', local: 'ราคาเท่าไหร่?', phon: 'ra-KAH tao-RAI' },
    { en: 'I need a taxi', local: 'ต้องการแท็กซี่', phon: 'dtong-GAHN TAEK-see' },
    { en: 'I need a doctor', local: 'ต้องการหมอ', phon: 'dtong-GAHN mor' },
    { en: 'Help!', local: 'ช่วยด้วย!', phon: 'chuay DUAY' },
    { en: 'Water', local: 'น้ำ', phon: 'nahm' },
    { en: 'The check, please', local: 'เช็คบิล', phon: 'chek BIN' },
    { en: 'Left / Right / Straight', local: 'ซ้าย / ขวา / ตรงไป', phon: 'SAI / KWAH / dtrong-BPai' },
    { en: 'I\'m lost', local: 'ฉันหลงทาง', phon: 'chan LONG tahng' },
    { en: 'Can you help me?', local: 'ช่วยได้ไหม?', phon: 'chuay DAI mai' },
    { en: 'Do you accept Bitcoin?', local: 'รับ Bitcoin ไหม?', phon: 'rap Bitcoin mai' },
  ]},
};

export const TRANSPORT_LINKS = [
  { emoji: '✈️', label: 'Flights', url: 'https://www.skyscanner.com/?utm_source=kipita&utm_medium=app&utm_campaign=KIPITA10' },
  { emoji: '🏨', label: 'Hotels', url: 'https://www.hotels.com/affiliate/RrZ7bmg' },
  { emoji: '🏨', label: 'Expedia', url: 'https://expedia.com/affiliate/eA2cKky' },
  { emoji: '🚗', label: 'Car Rental', url: 'https://www.rentalcars.com/?utm_source=kipita&utm_medium=app' },
  { emoji: '🚢', label: 'Cruise', url: 'https://www.expedia.com/?siteid=1&langid=1033&clickref=1110l34GXzfF&affcid=US.DIRECT.PHG.1100l360011.1100l68075&ref_id=1110l34GXzfF&my_ad=AFF.US.DIRECT.PHG.1100l360011.1100l68075&afflid=1110l34GXzfF&affdtl=PHG.1110l34GXzfF.PZ2TDkyK4w' },
  { emoji: '🚕', label: 'Uber', url: 'https://uber.com/?utm_source=kipita&utm_medium=app' },
  { emoji: '🛻', label: 'Lyft', url: 'https://lyft.com/?utm_source=kipita&utm_medium=app' },
];

export const BOOKING_TILES = [
  { emoji: '✈️', label: 'Flights', desc: 'Compare & book flights worldwide', url: 'https://www.skyscanner.com/?utm_source=kipita&utm_medium=app&utm_campaign=KIPITA10', provider: 'Skyscanner' },
  { emoji: '🏨', label: 'Hotels', desc: 'Best rates on 2M+ properties', url: 'https://www.booking.com/?utm_source=kipita&utm_medium=app&utm_campaign=KIPITAGENI', provider: 'Booking.com' },
  { emoji: '🏨', label: 'Expedia', desc: 'Bundle deals on flights + hotels', url: 'https://expedia.com/affiliate/eA2cKky', provider: 'Expedia' },
  { emoji: '🏨', label: 'Hotels.com', desc: 'Earn free nights on every 10 stays', url: 'https://www.hotels.com/affiliate/RrZ7bmg', provider: 'Hotels.com' },
  { emoji: '🏠', label: 'Stays', desc: 'Unique homes & apartments', url: 'https://www.airbnb.com/', provider: 'Airbnb' },
  { emoji: '🚗', label: 'Car Rental', desc: 'Vehicles in 60,000+ locations', url: 'https://www.rentalcars.com/?utm_source=kipita&utm_medium=app', provider: 'RentalCars' },
  { emoji: '🚢', label: 'Cruises', desc: 'Deals on cruises worldwide', url: 'https://www.expedia.com/?siteid=1&langid=1033&clickref=1110l34GXzfF&affcid=US.DIRECT.PHG.1100l360011.1100l68075&ref_id=1110l34GXzfF&my_ad=AFF.US.DIRECT.PHG.1100l360011.1100l68075&afflid=1110l34GXzfF&affdtl=PHG.1110l34GXzfF.PZ2TDkyK4w', provider: 'Expedia Cruises' },
  { emoji: '🛡️', label: 'Insurance', desc: 'Travel insurance for nomads', url: 'https://www.worldnomads.com/', provider: 'World Nomads' },
  { emoji: '📶', label: 'eSIM Data', desc: 'Instant data in 200+ countries', url: 'https://www.airalo.com/?utm_source=kipita&utm_medium=app&utm_campaign=KIPITA5', provider: 'Airalo' },
  { emoji: '🔐', label: 'VPN', desc: 'Secure connection worldwide', url: 'https://nordvpn.com/?utm_source=kipita&utm_medium=app&utm_campaign=KIPITAVPN', provider: 'NordVPN' },
];

export const SAVETRAVELDEALS = [
  { emoji: '✈️', label: 'Flights & Hotels', desc: 'Search and book at the best prices', url: 'https://savetraveldeals.com/book-hotels-app/' },
  { emoji: '🚗', label: 'Car Rental', desc: 'Rent a car anywhere in the world', url: 'https://savetraveldeals.com/car-rental-app/' },
  { emoji: '🚐', label: 'Airport Transfers', desc: 'Reliable airport transfer services', url: 'https://savetraveldeals.com/airport-transfers/' },
  { emoji: '🚲', label: 'Bike Rental', desc: 'Explore cities on two wheels', url: 'https://savetraveldeals.com/bike-rental-app/' },
];

export const PERKS = [
  { icon: '✈️', title: 'Skyscanner', desc: '10% off flights when booked through Kipita.', code: 'KIPITA10', expiry: 'Dec 2026', url: 'https://www.skyscanner.com/?utm_source=kipita&utm_medium=app&utm_campaign=KIPITA10', category: 'travel' },
  { icon: '🏨', title: 'Booking.com', desc: 'Genius Level 2 instant unlock — up to 20% off.', code: 'KIPITAGENI', expiry: 'Ongoing', url: 'https://www.booking.com/?utm_source=kipita&utm_medium=app&utm_campaign=KIPITAGENI', category: 'travel' },
  { icon: '🏨', title: 'Expedia', desc: 'Bundle & save on flights + hotels.', code: '', expiry: 'Ongoing', url: 'https://expedia.com/affiliate/eA2cKky', category: 'travel' },
  { icon: '🏨', title: 'Hotels.com', desc: 'Earn a free night for every 10 stays.', code: '', expiry: 'Ongoing', url: 'https://www.hotels.com/affiliate/RrZ7bmg', category: 'travel' },
  { icon: '🏠', title: 'Airbnb', desc: '$25 off your first stay with Kipita referral.', code: 'KIPITABNB', expiry: 'Mar 2027', url: 'https://www.airbnb.com/', category: 'travel' },
  { icon: '🚢', title: 'Expedia Cruises', desc: 'Exclusive nomad cruise deals + onboard credits.', code: 'KIPITACRUISE', expiry: 'Ongoing', url: 'https://www.expedia.com/?siteid=1&langid=1033&clickref=1110l34GXzfF&affcid=US.DIRECT.PHG.1100l360011.1100l68075&ref_id=1110l34GXzfF&my_ad=AFF.US.DIRECT.PHG.1100l360011.1100l68075&afflid=1110l34GXzfF&affdtl=PHG.1110l34GXzfF.PZ2TDkyK4w', category: 'travel' },
  { icon: '🚕', title: 'Uber', desc: 'Rides worldwide — fast & reliable.', code: '', expiry: 'Ongoing', url: 'https://uber.com/?utm_source=kipita&utm_medium=app', category: 'travel' },
  { icon: '🛻', title: 'Lyft', desc: 'Affordable rides across North America.', code: '', expiry: 'Ongoing', url: 'https://lyft.com/?utm_source=kipita&utm_medium=app', category: 'travel' },
  { icon: '🦢', title: 'Swan Bitcoin', desc: 'Auto-stack sats — $10 free Bitcoin on signup.', code: 'KIPITASWAN', expiry: 'Dec 2026', url: 'https://www.swanbitcoin.com/kipita/', category: 'btc' },
  { icon: '💳', title: 'Fold Card', desc: 'Earn BTC rewards on every purchase. Spin the wheel daily.', code: 'MAJL4MYU', expiry: 'Ongoing', url: 'https://use.foldapp.com/r/MAJL4MYU', category: 'btc' },
  
  
  { icon: '🥇', title: 'Kinesis', desc: 'Gold & silver-backed digital currency. Trade precious metals.', code: 'KM00083150', expiry: 'Ongoing', url: 'https://kms.kinesis.money/signup/KM00083150', category: 'btc' },
  { icon: '⛽', title: 'Upside', desc: 'Cash back on gas, food & groceries.', code: '', expiry: 'Ongoing', url: 'https://upside.com/', category: 'btc' },
  { icon: '🗺️', title: 'BTCMap', desc: 'Find Bitcoin merchants worldwide.', code: '', expiry: 'Ongoing', url: 'https://btcmap.org/?utm_source=kipita&utm_medium=app', category: 'btc' },
  { icon: '💻', title: 'NomadList Pro', desc: '3 months free NomadList Pro subscription.', code: 'KIPITANOMAD', expiry: 'Mar 2027', url: 'https://nomadlist.com/?utm_source=kipita&utm_medium=app&utm_campaign=KIPITANOMAD', category: 'tools' },
  { icon: '📶', title: 'Airalo eSIM', desc: '5% off any eSIM data plan worldwide.', code: 'KIPITA5', expiry: 'Jun 2026', url: 'https://www.airalo.com/?utm_source=kipita&utm_medium=app&utm_campaign=KIPITA5', category: 'tools' },
  { icon: '🏋️', title: 'ClassPass', desc: 'First month free — access gyms, yoga and fitness globally.', code: 'KIPITAFIT', expiry: 'Ongoing', url: 'https://classpass.com/?utm_source=kipita&utm_medium=app&utm_campaign=KIPITAFIT', category: 'tools' },
  { icon: '🔐', title: 'NordVPN', desc: '2-year plan at 70% off. Secure your connection.', code: 'KIPITAVPN', expiry: 'Dec 2026', url: 'https://nordvpn.com/?utm_source=kipita&utm_medium=app&utm_campaign=KIPITAVPN', category: 'tools' },
  { icon: '🛡️', title: 'World Nomads', desc: 'Travel insurance built for nomads. 10% off with code.', code: 'KIPITASAFE', expiry: 'Ongoing', url: 'https://www.worldnomads.com/', category: 'tools' },
  { icon: '💼', title: 'Wise', desc: 'Multi-currency account. First transfer free.', code: 'KIPITAWISE', expiry: 'Ongoing', url: 'https://wise.com/', category: 'tools' },
];

export const DEMO_REVIEWS = [
  { id: 'r1', author: 'Alex M.', flag: '🇺🇸', dest: 'Bangkok', emoji: '🛕', rating: 5, wifi: 5, budget: 5, vibe: 4, text: "Bangkok is unreal for nomads. Lightning-fast fiber at every cafe, street food for $2, and you can pay BTC at loads of spots." },
  { id: 'r2', author: 'Sara K.', flag: '🇬🇧', dest: 'Bali', emoji: '🌴', rating: 4, wifi: 3, budget: 4, vibe: 5, text: "Canggu has the best nomad community on earth. The vibe is incredible, co-working spaces everywhere." },
  { id: 'r3', author: 'Marco B.', flag: '🇮🇹', dest: 'Lisbon', emoji: '🇵🇹', rating: 5, wifi: 4, budget: 3, vibe: 5, text: "Europe's best city for nomads right now. NHR tax regime, incredible food, great tech scene." },
  { id: 'r4', author: 'Yuki T.', flag: '🇯🇵', dest: 'Tokyo', emoji: '🗼', rating: 5, wifi: 5, budget: 2, vibe: 5, text: "Tokyo is the most organised city in the world. Thousands of BTC merchants, insane food, 100% safe." },
  { id: 'r5', author: 'Priya N.', flag: '🇮🇳', dest: 'Chiang Mai', emoji: '🏔️', rating: 5, wifi: 5, budget: 5, vibe: 4, text: "$800/month comfortable lifestyle. Best Internet cafes in the world." },
  { id: 'r6', author: 'Leo C.', flag: '🇨🇦', dest: 'Medellín', emoji: '🌺', rating: 4, wifi: 4, budget: 5, vibe: 5, text: "Spring weather all year, incredible food, and a booming crypto scene." },
];

export const GROUPS: Group[] = [
  { id: '1', name: 'BTC Nomads 🌍', emoji: '₿', members: 342, lastMessage: 'Anyone know good BTC cafes in Lisbon?', unread: 3, messages: [
    { id: 'm1', sender: 'SatoshiTraveler', text: 'Anyone know good BTC cafes in Lisbon?', mine: false, time: '10:30 AM' },
    { id: 'm2', sender: 'PortugalNomad', text: 'Check out Copenhagen Coffee Lab — they accept Lightning!', mine: false, time: '10:32 AM' },
    { id: 'm3', sender: 'You', text: 'Also try Zenith Brunch & Cocktails, great vibe 🔥', mine: true, time: '10:35 AM' },
  ]},
  { id: '2', name: 'SE Asia Digital Nomads', emoji: '🌴', members: 1205, lastMessage: 'New coworking space opened in Canggu!', unread: 7, messages: [
    { id: 'm4', sender: 'BaliRemote', text: 'New coworking space opened in Canggu!', mine: false, time: '9:15 AM' },
    { id: 'm5', sender: 'ChiangMaiDev', text: "What's the day rate?", mine: false, time: '9:20 AM' },
  ]},
  { id: '3', name: 'Safety Alerts Network', emoji: '🛡️', members: 890, lastMessage: 'Flooding advisory lifted for Bangkok', unread: 0, messages: [
    { id: 'm6', sender: 'SafetyBot', text: 'Flooding advisory lifted for Bangkok. All clear! ✅', mine: false, time: 'Yesterday' },
  ]},
  { id: '4', name: 'Budget Travelers Club', emoji: '💰', members: 567, lastMessage: '$15/night hostels in Medellín 🔥', unread: 2, messages: [
    { id: 'm7', sender: 'BudgetKing', text: '$15/night hostels in Medellín 🔥', mine: false, time: '8:00 AM' },
  ]},
];

/* ── AI RESPONSES (matching latest build + deep trip integration) ── */
export const AI_RESPONSES = {
  plan: (dest: string) => `✈️ **Trip Plan: ${dest || 'Your Dream Destination'}**\n\n**Day 1: Arrival & Orientation**\n• Check into your accommodation\n• Explore the local neighborhood on foot\n• Try street food or a local restaurant\n• Currency exchange and SIM card setup\n\n**Day 2: Culture & History**\n• Morning: Visit main historical landmarks\n• Afternoon: Local markets or museum\n• Evening: Sunset viewpoint + dinner\n\n**Day 3: Off the Beaten Path**\n• Day trip to nearby nature or town\n• Connect with local nomads at a co-working space\n• Try Bitcoin payments at local merchants (BTCMap)\n\n**Day 4: Food & Community**\n• Cooking class or food tour\n• Social events / meetups\n• Evening: Night market or bar crawl\n\n**Day 5: Departure**\n• Final shopping and souvenirs\n• Airport transfer via Uber/Lyft\n\n📦 **Book Your Trip:**\n• ✈️ Flights → [Expedia](https://expedia.com/affiliate/eA2cKky)\n• 🏨 Hotels → [Hotels.com](https://www.hotels.com/affiliate/RrZ7bmg)\n• 🚢 Cruises → [Expedia Cruises](https://www.expedia.com/?siteid=1&langid=1033&clickref=1110l34GXzfF&affcid=US.DIRECT.PHG.1100l360011.1100l68075&ref_id=1110l34GXzfF&my_ad=AFF.US.DIRECT.PHG.1100l360011.1100l68075&afflid=1110l34GXzfF&affdtl=PHG.1110l34GXzfF.PZ2TDkyK4w)\n\n₿ **BTC & Finance:**\n• 🦢 Stack sats → [Swan Bitcoin](https://www.swanbitcoin.com/kipita/) — $10 free BTC on signup\n• 💳 BTC rewards → [Fold Card](https://use.foldapp.com/r/MAJL4MYU) — earn Bitcoin on every purchase\n• 🥇 Gold & silver → [Kinesis](https://kms.kinesis.money/signup/KM00083150) — trade precious metals\n• ⛽ Cash back → [Upside](https://upside.com/) — save on gas, food & groceries`,

  safety: (loc: string) => `🛡️ **Safety Overview — ${loc}**\n\n**General Safety Tips:**\n• Keep digital copies of all documents\n• Use a VPN on public WiFi\n• Register with your embassy\n• Share your itinerary with someone at home\n• Keep emergency numbers saved offline\n\n**Emergency Resources:**\n• 🚨 Tap the Emergency 🚨 button in the header for numbers\n• 🏥 Find nearest hospital in the **Places** tab\n• 📱 Offline maps available for download\n\n*Always check your government's travel advisory before traveling.*`,

  advisories: () => `📋 **Current Travel Advisories (2026)**\n\n🟢 **Low Risk:** Japan, Singapore, Portugal, UAE, Iceland\n🟡 **Exercise Caution:** Thailand, Mexico, Colombia, India\n🟠 **Elevated Caution:** South Africa, Kenya, Turkey\n🔴 **Reconsider Travel:** Myanmar, Sudan, Haiti\n\n⚠️ *These are general advisories. Always check your government's official portal for the most current information.*`,

  phrases: () => `🌐 **Essential Travel Phrases**\n\nOpen the **Places → Phrases** section for 10 languages with 20+ survival phrases each!\n\nCovers: Spanish, Mandarin, French, Arabic, Hindi, Portuguese, Japanese, German, Korean & Thai.\n\nQuick essentials:\n• Hello / Goodbye / Please / Thank you\n• Where is the bathroom? / airport?\n• I need a taxi / doctor\n• Left / Right / Straight\n• I\'m lost / Can you help me?\n\n*Tip: Screenshot phrases for offline access!*`,

  perks: () => `🎁 **Kipita Perks & Deals**\n\n**✈️ Travel:**\n• [Expedia](https://expedia.com/affiliate/eA2cKky) — Bundle & save on flights + hotels\n• [Hotels.com](https://www.hotels.com/affiliate/RrZ7bmg) — Earn a free night for every 10 stays\n• [Expedia Cruises](https://www.expedia.com/?siteid=1&langid=1033&clickref=1110l34GXzfF&affcid=US.DIRECT.PHG.1100l360011.1100l68075&ref_id=1110l34GXzfF&my_ad=AFF.US.DIRECT.PHG.1100l360011.1100l68075&afflid=1110l34GXzfF&affdtl=PHG.1110l34GXzfF.PZ2TDkyK4w) — Cruise deals worldwide\n\n**₿ Bitcoin & Finance:**\n• [Swan Bitcoin](https://www.swanbitcoin.com/kipita/) — $10 free BTC on signup\n• [Fold Card](https://use.foldapp.com/r/MAJL4MYU) — Earn BTC rewards on every purchase\n• [Kinesis](https://kms.kinesis.money/signup/KM00083150) — Gold & silver-backed digital currency\n• [Upside](https://upside.com/) — Cash back on gas, food & groceries`,

  default: (topic: string) => `Great question about "${topic}"! As your AI travel companion, I can help with:\n\n✈️ **Trip Planning** — Custom itineraries with booking links\n🛡️ **Safety Info** — Real-time advisories & emergency contacts\n₿ **Bitcoin** — Find BTC-friendly spots + Swan, Fold, Kinesis deals\n🌐 **Phrases** — 20+ survival phrases in 10 languages\n🗺️ **Destinations** — Nomad scores, costs, weather\n💱 **Currency** — Live exchange rates & converter\n🎁 **Perks** — Exclusive deals for flights, hotels & crypto\n🎒 **Packing** — Smart packing lists\n\nTry asking me to "Plan a trip to Tokyo" or "Show me perks and deals" 🌍`,
};

/* ── DEMO PLACE GENERATION (matching latest build) ───────── */
const placeNames: Record<string, string[]> = {
  food: ['Nomad Kitchen', 'Street Bites', 'The Wanderer Grill', 'Local Eats', 'Spice Route', 'Fusion Corner'],
  cafe: ['Digital Nomad Café', 'Bean & Browse', 'The Grind', 'Pour Over Paradise', 'Roast & Relax', 'Brew Corner'],
  hotel: ['Nomad Hostel', 'The Co-Living Hub', 'Modern Suites', 'Budget Inn', 'Artisan Rooms', 'City Stay'],
  transport: ['City Metro', 'Express Bus', 'BTS Station', 'MRT Hub', 'Tuk-Tuk Stand', 'Grab Point'],
  atm: ['BTC ATM', 'Lightning ATM', 'Crypto Kiosk', 'Exchange Point', 'Bitcoin Corner', 'Crypto ATM'],
  shop: ['Local Market', 'Nomad Shop', 'Night Bazaar', 'Weekend Market', 'Tech Store', 'Street Market'],
  gym: ['Nomad Gym', 'FitHub', 'Iron Zone', 'CrossFit Box', 'Yoga Studio', 'Sports Club'],
  beach: ['Sunset Beach', 'Chill Cove', 'Digital Nomad Beach', 'Surf Spot', 'Kite Beach', 'Hidden Bay'],
  nightlife: ['Rooftop Bar', 'Night Market', 'Jazz Lounge', 'Sky Bar', 'Night Club', 'Live Music Venue'],
  default: ['Place 1', 'Place 2', 'Place 3', 'Place 4', 'Place 5', 'Place 6'],
};
const streets = ['Main Street', 'Market Ave', 'Digital Lane', 'Nomad Road', 'BTC Boulevard', 'Satoshi St'];

export function generateDemoPlaces(query: string, label: string, count: number, locationName: string) {
  const cat = query.includes('restaurant') || query.includes('food') ? 'food'
    : query.includes('cafe') || query.includes('coffee') ? 'cafe'
    : query.includes('hotel') || query.includes('hostel') ? 'hotel'
    : query.includes('transit') || query.includes('transport') || query.includes('bus') || query.includes('metro') ? 'transport'
    : query.includes('bitcoin') || query.includes('atm') || query.includes('crypto') ? 'atm'
    : query.includes('shopping') || query.includes('market') ? 'shop'
    : query.includes('gym') || query.includes('fitness') ? 'gym'
    : query.includes('beach') ? 'beach'
    : query.includes('nightlife') || query.includes('bar') ? 'nightlife'
    : 'default';
  const emojis: Record<string, string> = { food: '🍜', cafe: '☕', hotel: '🏨', transport: '🚇', atm: '₿', shop: '🛍', gym: '💪', beach: '🏖️', nightlife: '🎵', default: '📍' };
  const names = placeNames[cat] || placeNames.default;
  const cityStreets = locationName && locationName !== 'Detecting…'
    ? streets.map(s => s + ', ' + locationName.split(',')[0])
    : streets;
  return Array.from({ length: count }, (_, i) => ({
    emoji: emojis[cat],
    name: names[i % names.length],
    addr: `${Math.floor(Math.random() * 200) + 1} ${cityStreets[i % cityStreets.length]}`,
    rating: (3.8 + Math.random() * 1.1).toFixed(1),
    dist: (0.2 + Math.random() * 4).toFixed(1),
    isOpen: Math.random() > 0.3,
    reviews: Math.floor(20 + Math.random() * 200),
    price: ['$', '$$', '$$$'][Math.floor(Math.random() * 3)],
  }));
}
