// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/search-places.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-places.ts
var search_places_default = defineTool({
  name: "search_places",
  title: "Search places near a location",
  description: "Find restaurants, cafes, ATMs, gas stations, hotels, pharmacies and other places near a latitude/longitude. Use `category` for a category sweep (ranked by distance) or `query` for a free-text search.",
  inputSchema: {
    lat: z.number().describe("Latitude of the search center."),
    lng: z.number().describe("Longitude of the search center."),
    category: z.string().optional().describe("Category keyword such as restaurant, cafe, atm, bank, gas, pharmacy, hotel, museum, park, bar."),
    query: z.string().optional().describe("Free-text search, e.g. 'French restaurant' or 'vegan brunch'. Takes precedence over category."),
    radius_meters: z.number().optional().describe("Search radius in meters. Defaults to 3500 for category search, 12000 for text search.")
  },
  annotations: { readOnlyHint: true, openWorldHint: true },
  handler: async ({ lat, lng, category, query, radius_meters }) => {
    const action = query ? "search" : "nearby";
    const body = {
      action,
      lat,
      lng,
      radius: radius_meters ?? (query ? 12e3 : 3500)
    };
    if (query) body.query = query;
    else body.category = category ?? "restaurant";
    const key = supabasePublishableKey();
    const res = await fetch(`${supabaseProjectUrl()}/functions/v1/places-proxy`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        apikey: key,
        Authorization: `Bearer ${key}`
      },
      body: JSON.stringify(body)
    });
    if (!res.ok) throw new ToolError(`Place search failed (${res.status})`);
    const json = await res.json();
    const raw = Array.isArray(json) ? json : json.places ?? [];
    const places = raw.slice(0, 15).map((p) => ({
      name: p.name,
      address: p.address,
      lat: p.lat,
      lng: p.lng,
      rating: p.rating ?? null,
      reviews: p.reviewCount ?? 0,
      openNow: p.openNow ?? null,
      phone: p.phone ?? null,
      website: p.website ?? null,
      type: p.typeLabel ?? null,
      mapsUrl: p.mapsUrl ?? null
    }));
    if (places.length === 0) {
      return { content: [{ type: "text", text: "No places found for that search." }] };
    }
    const text = places.map(
      (p, i) => `${i + 1}. ${p.name}${p.rating ? ` (${p.rating}\u2605, ${p.reviews} reviews)` : ""} \u2014 ${p.address}${p.openNow === true ? " \xB7 open now" : p.openNow === false ? " \xB7 closed" : ""}`
    ).join("\n");
    return { content: [{ type: "text", text }], structuredContent: { places } };
  }
});

// src/lib/mcp/tools/geocode-place.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^4.4.3";
var geocode_place_default = defineTool2({
  name: "geocode_place",
  title: "Geocode a city or address",
  description: "Turn a city, address or landmark name into latitude/longitude plus country, so other tools can be called with coordinates.",
  inputSchema: {
    query: z2.string().describe("City, address or landmark, e.g. 'Albuquerque NM' or 'Echo Beach Bali'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query }) => {
    const url = "https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&limit=3&q=" + encodeURIComponent(query.trim());
    const res = await fetch(url, { headers: { "User-Agent": "Kipita-MCP/1.0" } });
    if (!res.ok) throw new ToolError2(`Geocoding failed (${res.status})`);
    const rows = await res.json();
    const results = rows.map((r) => ({
      label: r.display_name ?? query,
      lat: Number(r.lat),
      lng: Number(r.lon),
      country: r.address?.country ?? null,
      countryCode: r.address?.country_code?.toUpperCase() ?? null
    }));
    if (results.length === 0) {
      return { content: [{ type: "text", text: `No location found for "${query}".` }] };
    }
    const text = results.map((r) => `${r.label} \u2014 ${r.lat.toFixed(4)}, ${r.lng.toFixed(4)}${r.country ? ` (${r.country})` : ""}`).join("\n");
    return { content: [{ type: "text", text }], structuredContent: { results } };
  }
});

// src/lib/mcp/tools/get-weather.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^4.4.3";
var get_weather_default = defineTool3({
  name: "get_weather_forecast",
  title: "Get weather forecast",
  description: "Current conditions plus a multi-day forecast (high/low, precipitation chance) for a latitude/longitude.",
  inputSchema: {
    lat: z3.number().describe("Latitude."),
    lng: z3.number().describe("Longitude."),
    days: z3.number().optional().describe("Forecast days, 1-7. Defaults to 7.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ lat, lng, days }) => {
    const span = Math.min(Math.max(Math.round(days ?? 7), 1), 7);
    const url = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lng}&current=temperature_2m,weather_code,wind_speed_10m&daily=temperature_2m_max,temperature_2m_min,precipitation_probability_max,weather_code&forecast_days=${span}&timezone=auto&temperature_unit=fahrenheit`;
    const res = await fetch(url);
    if (!res.ok) throw new ToolError3(`Weather lookup failed (${res.status})`);
    const j = await res.json();
    const daily = (j.daily?.time ?? []).map((date, i) => ({
      date,
      highF: j.daily.temperature_2m_max?.[i] ?? null,
      lowF: j.daily.temperature_2m_min?.[i] ?? null,
      precipChance: j.daily.precipitation_probability_max?.[i] ?? null
    }));
    const current = {
      temperatureF: j.current?.temperature_2m ?? null,
      windMph: j.current?.wind_speed_10m ?? null
    };
    const text = [
      `Now: ${current.temperatureF ?? "?"}\xB0F, wind ${current.windMph ?? "?"} mph`,
      ...daily.map(
        (d) => `${d.date}: ${d.lowF ?? "?"}\u2013${d.highF ?? "?"}\xB0F, precip ${d.precipChance ?? 0}%`
      )
    ].join("\n");
    return { content: [{ type: "text", text }], structuredContent: { current, daily } };
  }
});

// src/lib/mcp/tools/list-saved-locations.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_saved_locations_default = defineTool4({
  name: "list_saved_locations",
  title: "List my saved locations",
  description: "List the locations the signed-in user has saved in the app, newest first.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("saved_locations").select("id,name,full_address,lat,lng,country_code,created_at").order("created_at", { ascending: false }).limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? rows.map((r) => `${r.name} \u2014 ${r.full_address ?? ""} (${r.lat}, ${r.lng})`.trim()).join("\n") : "No saved locations yet.";
    return { content: [{ type: "text", text }], structuredContent: { locations: rows } };
  }
});

// src/lib/mcp/tools/save-location.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^4.4.3";
var save_location_default = defineTool5({
  name: "save_location",
  title: "Save a location",
  description: "Save a location (name, address, coordinates) to the signed-in user's saved locations in the app.",
  inputSchema: {
    name: z4.string().trim().describe("Short label for the location, e.g. 'Home' or 'Le Chene'."),
    lat: z4.number().describe("Latitude."),
    lng: z4.number().describe("Longitude."),
    full_address: z4.string().optional().describe("Full street address, when known."),
    country_code: z4.string().optional().describe("Two-letter country code, e.g. US.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ name, lat, lng, full_address, country_code }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!name.trim()) {
      return { content: [{ type: "text", text: "A location name is required." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("saved_locations").insert({
      user_id: ctx.getUserId(),
      name: name.trim(),
      lat,
      lng,
      full_address: full_address ?? null,
      country_code: country_code ? country_code.toUpperCase().slice(0, 2) : null
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved "${data.name}".` }],
      structuredContent: { location: data }
    };
  }
});

// src/lib/mcp/tools/list-business-listings.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.2";
var list_business_listings_default = defineTool6({
  name: "list_my_business_listings",
  title: "List my business listings",
  description: "List the business listings owned by the signed-in user, including verification status.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("business_listings").select("id,name,category,address,phone,website,status,description,created_at").order("created_at", { ascending: false }).limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const text = rows.length ? rows.map((r) => `${r.name} (${r.category}) \u2014 ${r.address} \xB7 status: ${r.status}`).join("\n") : "No business listings yet.";
    return { content: [{ type: "text", text }], structuredContent: { listings: rows } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jdncnzllpuvixnivpcos";
var mcp_default = defineMcp({
  name: "my-github-hub",
  title: "My GitHub Hub",
  version: "0.1.0",
  instructions: "Travel and local-discovery tools for this app. Use `geocode_place` to turn a city or address into coordinates, then `search_places` for nearby restaurants, cafes, ATMs, gas stations, hotels and more (ranked by distance), and `get_weather_forecast` for conditions. For the signed-in user, `list_saved_locations` and `save_location` manage their saved places, and `list_my_business_listings` returns the businesses they own.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_places_default,
    geocode_place_default,
    get_weather_default,
    list_saved_locations_default,
    save_location_default,
    list_business_listings_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
